"use client";

import { useRouter } from "next/navigation";
import { Download, Eye, FileText, IndianRupee, Calendar } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import type { SalarySlipItem } from "@/types/salarySlip";

interface EmployeeSalarySlipsPanelProps {
  slips: SalarySlipItem[];
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(amount);
}

function SlipCard({ slip }: { slip: SalarySlipItem }) {
  const router = useRouter();

  return (
    <Card className="group hover:shadow-md transition-shadow duration-200">
      <CardContent className="pt-5 pb-5">
        <div className="flex items-start justify-between gap-3 mb-4">
          <div className="flex items-center gap-3">
            <div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10">
              <FileText className="size-5 text-primary" />
            </div>
            <div>
              <div className="font-semibold text-foreground text-sm leading-tight">
                {slip.monthName} {slip.year}
              </div>
              <div className="text-xs text-muted-foreground mt-0.5">Salary Slip</div>
            </div>
          </div>
          <Badge variant="secondary" className="text-xs shrink-0">
            {slip.monthName.slice(0, 3)} &apos;{String(slip.year).slice(2)}
          </Badge>
        </div>

        {/* Net Pay Highlight */}
        <div className="rounded-lg bg-gradient-to-br from-[#1e3a5f] to-[#0f2444] px-4 py-3 mb-4">
          <p className="text-[10px] text-white/50 uppercase tracking-wider mb-0.5">Net Pay</p>
          <p className="text-lg font-bold text-orange-400">{formatCurrency(slip.netSalary)}</p>
        </div>

        {/* Quick stats */}
        <div className="grid grid-cols-3 gap-2 mb-4 text-center">
          <div className="rounded-md bg-muted/50 px-2 py-1.5">
            <p className="text-[10px] text-muted-foreground">Basic</p>
            <p className="text-xs font-semibold truncate">
              {formatCurrency(slip.basicSalary)}
            </p>
          </div>
          <div className="rounded-md bg-muted/50 px-2 py-1.5">
            <p className="text-[10px] text-muted-foreground">Allowances</p>
            <p className="text-xs font-semibold truncate">
              {formatCurrency(slip.allowances)}
            </p>
          </div>
          <div className="rounded-md bg-red-50 px-2 py-1.5">
            <p className="text-[10px] text-muted-foreground">Deductions</p>
            <p className="text-xs font-semibold text-red-600 truncate">
              −{formatCurrency(slip.deductions)}
            </p>
          </div>
        </div>

        {/* Actions */}
        <div className="flex gap-2">
          <Button
            size="sm"
            variant="outline"
            className="flex-1 gap-1.5 h-8 text-xs"
            onClick={() => router.push(`/salary-slips/${slip.id}`)}
          >
            <Eye className="size-3.5" />
            View
          </Button>
          <Button
            size="sm"
            className="flex-1 gap-1.5 h-8 text-xs"
            onClick={() => window.open(`/api/salary-slips/${slip.id}/pdf`, "_blank")}
          >
            <Download className="size-3.5" />
            Download
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

export function EmployeeSalarySlipsPanel({ slips }: EmployeeSalarySlipsPanelProps) {
  if (slips.length === 0) {
    return (
      <div className="mx-auto flex w-full max-w-lg flex-1 items-center justify-center">
        <div className="flex flex-col items-center gap-4 text-center py-16">
          <div className="flex size-16 items-center justify-center rounded-2xl bg-muted">
            <FileText className="size-8 text-muted-foreground" />
          </div>
          <div>
            <h2 className="text-base font-semibold text-foreground">No salary slips yet</h2>
            <p className="text-sm text-muted-foreground mt-1">
              Your salary slips will appear here once they are generated by your admin.
            </p>
          </div>
        </div>
      </div>
    );
  }

  // Compute total YTD for the latest year
  const latestYear = Math.max(...slips.map((s) => s.year));
  const ytdTotal = slips
    .filter((s) => s.year === latestYear)
    .reduce((sum, s) => sum + s.netSalary, 0);

  return (
    <div className="space-y-6">
      {/* ── Header ── */}
      <div className="flex items-start justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-xl font-bold text-foreground">My Salary Slips</h1>
          <p className="text-sm text-muted-foreground mt-0.5">
            View and download your monthly salary slips
          </p>
        </div>

        {/* YTD Summary */}
        <div className="flex items-center gap-3 rounded-xl bg-gradient-to-br from-[#1e3a5f] to-[#0f2444] px-5 py-3 shadow-md">
          <IndianRupee className="size-5 text-orange-400 shrink-0" />
          <div>
            <p className="text-[10px] text-white/50 uppercase tracking-wider">{latestYear} Total</p>
            <p className="text-base font-bold text-orange-400">{formatCurrency(ytdTotal)}</p>
          </div>
        </div>
      </div>

      {/* ── Slips Grid ── */}
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {slips.map((slip) => (
          <SlipCard key={slip.id} slip={slip} />
        ))}
      </div>
    </div>
  );
}
